# Generated by Django 4.2.2 on 2023-07-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservice',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addservice',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
